package ui;

import model.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Main JFrame for Lab 4 Application
 */
public class MainJFrame extends JFrame {
    
    private SupplierDirectory supplierDirectory;
    private JPanel mainWorkArea;
    
    public MainJFrame() {
        initializeData();
        initComponents();
        setupApplication();
    }
    
    private void initializeData() {
        supplierDirectory = new SupplierDirectory();
        
        // Add some sample suppliers for testing
        model.Supplier bestBuy = supplierDirectory.addSupplier();
        bestBuy.setSupplyName("Best Buy");
        
        model.Supplier mustBuy = supplierDirectory.addSupplier();
        mustBuy.setSupplyName("Must Buy");
        
        // Add sample products to Best Buy
        model.Product laptop = bestBuy.getProductCatalog().addProduct();
        laptop.setName("Gaming Laptop");
        laptop.setPrice(1200);
        laptop.addFeature(new model.Feature("RAM", "16GB"));
        laptop.addFeature(new model.Feature("Storage", "1TB SSD"));
        
        model.Product monitor = bestBuy.getProductCatalog().addProduct();
        monitor.setName("4K Monitor");
        monitor.setPrice(400);
        monitor.addFeature(new model.Feature("Resolution", "3840x2160"));
        monitor.addFeature(new model.Feature("Size", "27 inches"));
    }
    
    private void initComponents() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Lab 4 - Multi-Party Relationships Demo");
        setSize(800, 600);
        setLocationRelativeTo(null);
        
        // Create main work area with CardLayout
        mainWorkArea = new JPanel(new CardLayout());
        add(mainWorkArea);
    }
    
    private void setupApplication() {
        // Create and add login screen
        LoginScreen loginScreen = new LoginScreen(mainWorkArea, supplierDirectory);
        mainWorkArea.add("LoginScreen", loginScreen);
        
        // Show login screen
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "LoginScreen");
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                // Removed the problematic UIManager line
                new MainJFrame().setVisible(true);
            }
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
