/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history = new VitalSignHistory();
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCVSConsciousState = new javax.swing.ButtonGroup();
        LableTitle = new javax.swing.JLabel();
        LableDate = new javax.swing.JLabel();
        LableTemperature = new javax.swing.JLabel();
        LableBloodPressure = new javax.swing.JLabel();
        LablePulse = new javax.swing.JLabel();
        LableConciousState = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldDateTemperature = new javax.swing.JTextField();
        fieldDateBp = new javax.swing.JTextField();
        fieldDatePulse = new javax.swing.JTextField();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        OkButtonSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LableTitle.setBackground(new java.awt.Color(0, 0, 0));
        LableTitle.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        LableTitle.setText("Create Vital Sign");
        add(LableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 220, 30));

        LableDate.setText("Date");
        add(LableDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, -1));

        LableTemperature.setText("Temperature");
        add(LableTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, -1));

        LableBloodPressure.setText("Blood Pressure");
        add(LableBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        LablePulse.setText("Pulse");
        add(LablePulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, -1));

        LableConciousState.setText("Conscious State");
        add(LableConciousState, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 92, 170, 20));

        fieldDateTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDateTemperatureActionPerformed(evt);
            }
        });
        add(fieldDateTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 170, -1));
        add(fieldDateBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 170, -1));
        add(fieldDatePulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 170, -1));

        btnGroupCVSConsciousState.add(radioYes);
        radioYes.setSelected(true);
        radioYes.setText("Yes");
        radioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesActionPerformed(evt);
            }
        });
        add(radioYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, 30));

        btnGroupCVSConsciousState.add(radioNo);
        radioNo.setText("No");
        add(radioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 50, 30));

        OkButtonSave.setBackground(new java.awt.Color(204, 255, 204));
        OkButtonSave.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        OkButtonSave.setText("Save");
        OkButtonSave.setBorder(new javax.swing.border.MatteBorder(null));
        OkButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonSaveActionPerformed(evt);
            }
        });
        add(OkButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDateTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDateTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateTemperatureActionPerformed

    private void radioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYesActionPerformed

    private void OkButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonSaveActionPerformed
        
        String date = fieldDate.getText();
        float temperature = Float.parseFloat(fieldDateTemperature.getText());
        double bp = Double.parseDouble(fieldDateBp.getText());
        int pulse = Integer.parseInt(fieldDatePulse.getText());
        boolean isConscious;
        
        if(radioYes.isSelected()){
            isConscious = true;
        }
        else{
            isConscious = false;
        }
        
        VitalSign vs = history.addNewVital();
        vs.setDate(date);
        vs.setTemperature(temperature);
        vs.setPulse(pulse);
        vs.setBloodPressure(bp);
        vs.setIsConcious(isConscious);
        
        JOptionPane.showMessageDialog(radioNo, "New VitalSign added");
        
        fieldDate.setText("");
        fieldDateTemperature.setText("");
        fieldDateBp.setText("");
        fieldDatePulse.setText("");
    }//GEN-LAST:event_OkButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LableBloodPressure;
    private javax.swing.JLabel LableConciousState;
    private javax.swing.JLabel LableDate;
    private javax.swing.JLabel LablePulse;
    private javax.swing.JLabel LableTemperature;
    private javax.swing.JLabel LableTitle;
    private javax.swing.JButton OkButtonSave;
    private javax.swing.ButtonGroup btnGroupCVSConsciousState;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldDateBp;
    private javax.swing.JTextField fieldDatePulse;
    private javax.swing.JTextField fieldDateTemperature;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    // End of variables declaration//GEN-END:variables
}
