/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableVital = new javax.swing.JTable();
        ViewLable = new javax.swing.JLabel();
        LableDate = new javax.swing.JLabel();
        LableTemperature = new javax.swing.JLabel();
        LableBloodPressure = new javax.swing.JLabel();
        LablePulse = new javax.swing.JLabel();
        LableConciousState = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        LableStatus = new javax.swing.JLabel();
        ButtonView = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableVital.setBackground(new java.awt.Color(204, 204, 204));
        TableVital.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TableVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Consicious Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 520, 340));

        ViewLable.setBackground(new java.awt.Color(0, 0, 0));
        ViewLable.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        ViewLable.setText("View Vital Sign History");
        add(ViewLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 30));

        LableDate.setText("Date");
        add(LableDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        LableTemperature.setText("Temperature");
        add(LableTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        LableBloodPressure.setText("Blood Pressure");
        add(LableBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        LablePulse.setText("Pulse");
        add(LablePulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        LableConciousState.setText("Conscious State");
        add(LableConciousState, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 130, -1));

        fieldTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTemperatureActionPerformed(evt);
            }
        });
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 130, -1));
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 130, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 130, -1));
        add(LableStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 130, 20));

        ButtonView.setText("View");
        ButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewActionPerformed(evt);
            }
        });
        add(ButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        add(ButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTemperatureActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
       int selectedRow = TableVital.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to delete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel) TableVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        history.deleteVital(selectedVital);
        JOptionPane.showMessageDialog(this, "Vital Sign deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        populateTable();
        
        fieldDate.setText("");
        fieldTemperature.setText("");
        fieldBp.setText("");
        fieldPulse.setText("");
        LableStatus.setText("");
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewActionPerformed
        
        int selectedRow = TableVital.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_ButtonViewActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        if(selectedVital != null){
            fieldDate.setText(selectedVital.getDate());
            fieldTemperature.setText(String.valueOf(selectedVital.getTemperature()));
            fieldBp.setText(String.valueOf(selectedVital.getBloodPressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
           if (selectedVital.getIsConcious()) {
               LableStatus.setText("YES");
           }else{
               LableStatus.setText("NO");
           }
        }
    }
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) TableVital.getModel();
        model.setRowCount(0);
        
        for(VitalSign vs: history.getHistory() )
        {
            Object[] row = new Object[5];
            row[0] = vs;
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getBloodPressure();
            row[4] = vs.getIsConcious();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonView;
    private javax.swing.JLabel LableBloodPressure;
    private javax.swing.JLabel LableConciousState;
    private javax.swing.JLabel LableDate;
    private javax.swing.JLabel LablePulse;
    private javax.swing.JLabel LableStatus;
    private javax.swing.JLabel LableTemperature;
    private javax.swing.JTable TableVital;
    private javax.swing.JLabel ViewLable;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
