package ui;

import javax.swing.*;
import java.awt.*;
import model.AccountDirectory;

public class AccountManagerWorkAreaJPanel extends JPanel {
    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    private JButton btnCreateAccount;
    private JButton btnManageAccount;
    
    public AccountManagerWorkAreaJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.accountDirectory = accountDirectory;
        initComponents();
    }
    
    private void initComponents() {
        setLayout(new FlowLayout(FlowLayout.LEFT));
        setBackground(Color.LIGHT_GRAY);
        
        btnCreateAccount = new JButton("Create Account");
        btnCreateAccount.setPreferredSize(new Dimension(120, 30));
        btnCreateAccount.addActionListener(evt -> btnCreateAccountActionPerformed(evt));
        
        btnManageAccount = new JButton("Manage Account");
        btnManageAccount.setPreferredSize(new Dimension(120, 30));
        btnManageAccount.addActionListener(evt -> btnManageAccountActionPerformed(evt));
        
        add(btnCreateAccount);
        add(btnManageAccount);
    }
    
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer, accountDirectory);
        userProcessContainer.add("CreateAccountJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
    
    private void btnManageAccountActionPerformed(java.awt.event.ActionEvent evt) {
        ManageAccountsJPanel panel = new ManageAccountsJPanel(userProcessContainer, accountDirectory);
        userProcessContainer.add("ManageAccountsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

