package ui;

import javax.swing.*;
import java.awt.*;
import model.AccountDirectory;
import model.Account;

public class ViewAccountJPanel extends JPanel {
    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    private Account account;
    private JTextField txtRoutingNumber;
    private JTextField txtAccountNumber;
    private JTextField txtBankName;
    
    public ViewAccountJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory, Account account) {
        this.userProcessContainer = userProcessContainer;
        this.accountDirectory = accountDirectory;
        this.account = account;
        initComponents();
        displayAccountDetails();
    }
    
    private void initComponents() {
        setLayout(new BorderLayout());
        setBackground(Color.LIGHT_GRAY);
        
        // Back button
        JButton btnBack = new JButton("<<< Back");
        btnBack.addActionListener(evt -> btnBackActionPerformed(evt));
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        topPanel.add(btnBack);
        add(topPanel, BorderLayout.NORTH);
        
        // Form panel
        JPanel formPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        formPanel.setBackground(Color.LIGHT_GRAY);
        
        // Title
        JLabel title = new JLabel("View Account", JLabel.CENTER);
        title.setFont(new Font("Arial", Font.BOLD, 16));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2; gbc.insets = new Insets(20, 0, 20, 0);
        formPanel.add(title, gbc);
        
        gbc.gridwidth = 1;
        gbc.insets = new Insets(5, 5, 5, 5);
        
        // Routing Number
        gbc.gridx = 0; gbc.gridy = 1; gbc.anchor = GridBagConstraints.EAST;
        formPanel.add(new JLabel("Routing Number:"), gbc);
        txtRoutingNumber = new JTextField(15);
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        formPanel.add(txtRoutingNumber, gbc);
        
        // Account Number
        gbc.gridx = 0; gbc.gridy = 2; gbc.anchor = GridBagConstraints.EAST;
        formPanel.add(new JLabel("Account Number:"), gbc);
        txtAccountNumber = new JTextField(15);
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        formPanel.add(txtAccountNumber, gbc);
        
        // Bank Name
        gbc.gridx = 0; gbc.gridy = 3; gbc.anchor = GridBagConstraints.EAST;
        formPanel.add(new JLabel("Bank Name:"), gbc);
        txtBankName = new JTextField(15);
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        formPanel.add(txtBankName, gbc);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnSave = new JButton("Save");
        JButton btnCancel = new JButton("Cancel");
        
        btnSave.addActionListener(evt -> btnSaveActionPerformed(evt));
        btnCancel.addActionListener(evt -> btnCancelActionPerformed(evt));
        
        buttonPanel.add(btnSave);
        buttonPanel.add(btnCancel);
        
        gbc.gridx = 0; gbc.gridy = 4; gbc.gridwidth = 2; gbc.insets = new Insets(20, 0, 0, 0);
        formPanel.add(buttonPanel, gbc);
        
        add(formPanel, BorderLayout.CENTER);
    }
    
    private void displayAccountDetails() {
        if (account != null) {
            txtRoutingNumber.setText(account.getRoutingNumber());
            txtAccountNumber.setText(account.getAccountNumber());
            txtBankName.setText(account.getBankName());
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if (account != null) {
            account.setRoutingNumber(txtRoutingNumber.getText());
            account.setAccountNumber(txtAccountNumber.getText());
            account.setBankName(txtBankName.getText());
            
            JOptionPane.showMessageDialog(this, "Account updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            btnBackActionPerformed(evt);
        }
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        btnBackActionPerformed(evt);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

